version: '3.4'

networks:
  app:

services:
  actransitmap:
    image: ${DOCKER_REGISTRY-}actransitmap
    build:
      context: .
      dockerfile: AcTransitMap/Dockerfile
    networks:
      - app
    depends_on:
      - 'rabbitmq.service'

  rabbitmq.service:
    image: masstransit/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - app
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 20s
      retries: 10

  gtfsconsumer:
    image: ${DOCKER_REGISTRY-}gtfsconsumer
    build:
      context: .
      dockerfile: GtfsConsumer/Dockerfile
    networks:
      - app
    environment:
      - RABBIT_USER=guest
      - RABBIT_PASS=guest
    depends_on:
      - 'rabbitmq.service'