version: '3.4'

networks:
  app:

services:
  actransitmap:
    image: ${DOCKER_REGISTRY-}actransitmap
    build:
      context: .
      dockerfile: AcTransitMap/Dockerfile
    networks:
      - app
    ports:
      - "80:80"
      - "443:443"
    environment:
      - RABBIT_PASS=guest
      - RABBIT_USER=guest
      - MONGO_DB=actransitmap
      - MONGO_COLLECTION=positions
      - SEQ_URL=http://seq.service:5341
    depends_on:
      - 'rabbitmq.service'
      - 'seq.service'

  rabbitmq.service:
    image: masstransit/rabbitmq
    ports:
      - "15672:15672"
    networks:
      - app
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 20s
      retries: 10

  seq.service:
    image: datalust/seq:latest
    ports:
      - "81:80"
    networks:
      - app
    volumes:
      - /var/opt/seq/data:/data
    environment:
      - ACCEPT_EULA=Y

  gtfsconsumer:
    image: ${DOCKER_REGISTRY-}gtfsconsumer
    build:
      context: .
      dockerfile: GtfsConsumer/Dockerfile
    networks:
      - app
    environment:
      - RABBIT_USER=guest
      - RABBIT_PASS=guest
      - SEQ_URL=http://seq.service:5341
    depends_on:
      - 'rabbitmq.service'
      - 'seq.service'

  messageprocessor:
    image: ${DOCKER_REGISTRY-}messageprocessor
    build:
      context: .
      dockerfile: MessageProcessor/Dockerfile
    networks:
      - app
    environment:
      - RABBIT_USER=guest
      - RABBIT_PASS=guest
      - MONGO_DB=actransitmap
      - MONGO_COLLECTION=positions
      - SEQ_URL=http://seq.service:5341
    depends_on:
      - 'rabbitmq.service'
      - 'seq.service'