version: '3.4'

networks:
  app:

services:
  actransitmap:
    image: ${DOCKER_REGISTRY-}actransitmap
    build:
      context: .
      dockerfile: AcTransitMap/Dockerfile
    networks:
      - app
    ports:
      - "80:80"
      - "443:443"
    environment:
      - RABBIT_PASS=${RABBIT_PASS}
      - RABBIT_USER=${RABBIT_USER}
      - MONGO_CONNSTR=${MONGO_CONNSTR}
      - MONGO_DB=${MONGO_DB}
      - MONGO_COLLECTION=${MONGO_COLLECTION}
      - SEQ_URL=${SEQ_URL}
    depends_on:
      - 'rabbitmq.service'
      - 'seq.service'

  rabbitmq.service:
    image: masstransit/rabbitmq
    ports:
      - "15672:15672"
    networks:
      - app
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 20s
      retries: 10

  seq.service:
    image: datalust/seq:latest
    ports:
      - "81:80"
    networks:
      - app
    volumes:
      - /var/opt/seq/data:/data
    environment:
      - ACCEPT_EULA=Y

  gtfsconsumer:
    image: ${DOCKER_REGISTRY-}gtfsconsumer
    build:
      context: .
      dockerfile: GtfsConsumer/Dockerfile
    networks:
      - app
    environment:
      - RABBIT_PASS=${RABBIT_PASS}
      - RABBIT_USER=${RABBIT_USER}
      - SEQ_URL=${SEQ_URL}
      - ACTRANSIT_KEY=${ACTRANSIT_KEY}
      - FETCH_DELAY=10
    depends_on:
      - 'rabbitmq.service'
      - 'seq.service'

  messageprocessor:
    image: ${DOCKER_REGISTRY-}messageprocessor
    build:
      context: .
      dockerfile: MessageProcessor/Dockerfile
    networks:
      - app
    environment:
      - RABBIT_PASS=${RABBIT_PASS}
      - RABBIT_USER=${RABBIT_USER}
      - MONGO_CONNSTR=${MONGO_CONNSTR}
      - MONGO_DB=${MONGO_DB}
      - MONGO_COLLECTION=${MONGO_COLLECTION}
      - SEQ_URL=${SEQ_URL}
    depends_on:
      - 'rabbitmq.service'
      - 'seq.service'