version: '3.4'

networks:
  app:

services:
  actransitmap:
    image: ${DOCKER_REGISTRY-}actransitmap
    build:
      context: .
      dockerfile: AcTransitMap/Dockerfile
    networks:
      - app

  rabbitmq.service:
    image: masstransit/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - app
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 20s
      retries: 10
