# This is a basic workflow to help you get started with Actions

name: PR Labeler

# Controls when the action will run. 
on:
  pull_request:
    types: [ opened ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: PR Labeler
      # You may pin to the exact commit or the version.
      # uses: TimonVS/pr-labeler-action@bd0b592a410983316a454e3d48444608f028ec8e
      uses: TimonVS/pr-labeler-action@v3.1.0
      with:
        # The path for the label configurations
        configuration-path: .github/pr-labeler.yml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}